(define (domain Vehicle)
 (:requirements :strips :typing :fluents)
 (:types vehicle location)
 (:predicates (esta ?v - vehicle ?p - location)
              (accessible ?v - vehicle ?p1 ?p2 - location))
 (:functions (fuel-level)
             (fuel-used)
             (fuel-reserve)
             (toll)
             (value-toll)
             (fuel-required ?p1 ?p2 - location))
 (:action drive
          :parameters (?v - vehicle ?from ?to - location)
          :precondition (and (esta ?v ?from)
                        (accessible ?v ?from ?to)
                        (>= (fuel-level) (fuel-required ?from ?to))
                        )
          :effect (and (not (esta ?v ?from))
                       (esta ?v ?to)
                       (increase (fuel-used) (fuel-required ?from ?to))
                       (decrease (fuel-level) (fuel-required ?from ?to))
                       (assign (toll) (+ (toll) (value-toll))) 
                   )
 )
)
