(define (problem gripper2)
  (:domain gripper)
  (:objects ball1 ball2 ball3 ball4 ball5 ball6 - ball right left - gripper roomA roomB - local)
  (:init
    (atrobby roomA) 
    (atball ball2 roomA)
    (atball ball1 roomA)
    (atball ball3 roomA)
    (atball ball4 roomA)
    (atball ball5 roomA)
    (atball ball6 roomA)
    (free right)
    (free left)
    )
  
  (:goal (and (atball ball1 roomB) (atball ball2 roomB) 
  (atball ball3 roomB)
  (atball ball4 roomB)
  (atball ball5 roomB)
  (atball ball6 roomB)
  (atrobby roomB) 
  (free right) (free left)))
    
)