(define (problem Vehicle-example)
        (:domain Vehicle)
        (:objects
			car - vehicle
			Paris Berlin Rome Madrid - location)
		(:init
			(esta car Paris)
			(= (fuel-level) 200)
                        (= (fuel-reserve) 15)			
                        (= (toll) 0)
                        (= (value-toll) 13)
                        (accessible car Paris Berlin)
			(accessible car Berlin Rome)
			(accessible car Rome Madrid)
                        (accessible car Rome Paris)
			(= (fuel-required Paris Berlin) 40)
			(= (fuel-required Berlin Rome) 30)
			(= (fuel-required Rome Madrid) 50)
			(= (fuel-required Rome Paris) 35)
			(= (fuel-required Rome Berlin) 40)
			(= (fuel-required Berlin Paris) 40)
			(= (fuel-used) 0)
		)
		(:goal (and (esta car Madrid))
		)		
)