(define (problem hanoi3)
  (:domain hanoi)
  (:objects a b c - torre d1 d2 d3 ba bb bc - disco)
  (:init
    (maior ba d1)
    (maior ba d2)
    (maior ba d3)
    (maior bb d1)
    (maior bb d2)
    (maior bb d3)
    (maior bc d1)
    (maior bc d2)
    (maior bc d3)
    (maior d3 d1)
    (maior d3 d2)
    (maior d2 d1)
    (esta ba a)
    (esta bb b)
    (esta bc c)
    (esta d1 a)
    (esta d2 a)
    (esta d3 a)
    (cima d3 ba)
    (cima d2 d3)
    (cima d1 d2)
    (topo d1 a)
    (topo bb b)
    (topo bc c))
  
  (:goal (and (esta d1 c) (esta d2 c) (esta d3 c)))
)