(define (problem robo1)
  (:domain robo)
  (:objects roomA roomB - local)
  (:init
    (atrobby roomA) 
    (= (total-percorrido) 0)
    (= (gasolina) 100)
    (= (distancia roomA roomB) 8)
    (= (distancia roomB roomA) 8)
    (= (consumo roomA roomB) 15)
    (= (consumo roomB roomA) 15)
  ) 
  (:goal (and (atrobby roomB)))
)